language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

sudo: required

matrix:
  fast_finish: true

branches:
  only:
  - master

install:
  - npm install

cache:
  directories:
    - node_modules
